const products = [
    {
        id: 1,
        name: "SAFE GRIP 3",
        description: "Guantes de bombero.",
        price: 129.99,
        category: "Guantes",
        image: "/images/csm_rosenbauer_handschuh_SafeGrip3_Stulpe_55A7517_c328191c1a.jpg",
        brand: "Alta resistencia a cortes, Aún más movilidad y Más comodidad.",
        weight: "",
        color: "Azul oscuro y Colores arena.",
    },
    {
        id: 2,
        name: "GLOROS T1",
        description: "Guante para intervenciones técnicas de rescate.",
        price: 54.99,
        category: "Guantes",
        image: "/images/csm_Rosenbauer_Handschuhe_GLOROS-F10_Produkt_1e938fcfcf.jpg",
        brand: "Alta comodidad y tactilidad, Excelente resistencia a los cortes, Óptimo antideslizamiento y agarre seguro.",
        weight: "",
        color: "Rojo.",
    },
    {
        id: 3,
        name: "HEROS Titan",
        description: "Cascos de bombero.",
        price: 329.99,
        category: "Cascos",
        image: "/images/Captura_de_pantalla_2023-10-04_003016.jpg",
        brand: "Excelente estabilidad, mayor protección mecánica, Punto de gravedad optimizado.",
        weight: "1,4 kg.",
        color: "Azul, Negro, Blanco, Rojo y Amarillo.",
    },
    {
        id: 4,
        name: "HEROS Matrix",
        description: "casco para incendios forestales y rescates tecnicos",
        price: 294.99,
        category: "Cascos",
        image: "/images/csm_rosenbauer_helm_HEROS-matrix_rot_TH_188_02_cf15b32928.jpg",
        brand: "Construcción ligera, Peso reducido, Interior ergonómico, Fácil ajuste del tamaño de la cabeza desde el exterior",
        weight: "1kg.",
        color: "Azul, rojo, blanco y amarillo.",
    },
    {
        id: 5,
        name: "GAROS G10",
        description: "Ropa de protección Para incendios forestales y asistencia técnica.",
        price: 334.99,
        category: "Indumentaria",
        image: "/images/csm_rosenbauer_bekleidung_garos-g10-tr_widget-schwarzblau-gelb_01_2afd432ce7.jpg",
        brand: "Peso mínimo gracias a su diseño de una sola capa, Material transpirable con alta permeabilidad al vapor, Ergocut universal para garantizar la máxima libertad de movimiento y Ajuste de talla óptimo.",
        weight: "2kg.",
        color: "negro-azul/amarillo, negro/, dorado/amarillo.",
    },
    {
        id: 6,
        name: "FIRE MAX 3",
        description: "Protección y comodidad de la próxima generacion.",
        price: 699.99,
        category: "Indumentaria",
        image: "/images/csm_rosenbauer_bekleidung_firemax3_fm_344_nomexblau_07_688976ab35.jpg",
        brand: "Máxima protección, Gran comodidad, Corte deportivo y Peso reducido.",
        weight: "3.2kg.",
        color: "azul oscuro, rojo, dorado y azul oscuro.",
    },
    {
        id: 7,
        name: "BOROS B1",
        description: "Botas deslizantes.",
        price: 244.99,
        category: "Botas",
        image: "/images/csm_Rosenbauer_Feuerwehrstiefel_BOROS-B1_Box-Uebersicht_2fd69f0b7e.jpg",
        brand: "Manejo fácil, Peso reducido, Cuidado sencillo yRelación calidad-precio excelente",
        weight: "2.4kg",
        color: "Negro.",
    },
    {
        id: 8,
        name: "BOROS B3 Cross",
        description: "con Boa® Fit System.",
        price: 309.99,
        category: "Botas",
        image: "/images/csm_Rosenbauer_Feuerwehrstiefel_BOROS-B3-Cross_Box-Uebersicht_1df413a434.jpg",
        brand: "Caña inferior, Buena y rápida adaptabilidad, Manejo sencillo y Peso mínimo.",
        weight: "2.3kg.",
        color: "Negro.",
    },
    {
        id: 9,
        name: "Equipo de Respiración Autónomo G1",
        description: "La máscara G1 se ha diseñado sin componentes electrónicos.",
        price: 609.99,
        category: "ERA",
        image: "/images/40735027.jpg",
        brand: "La máscara es liviana y compacta, Tecnología integrada, Visibilidad mejorada a través de luces de apoyo y material reflectivo, Sistema de alimentación central para todos los componentes electrónicos, Disponible en versión para cilindro roscado o cilindro de conexión rápida.",
        weight: "4.8kg.",
        color: "Unico color.",
    },
];

export default products;
